name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite (UTC)
  workflow_dispatch: # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    # Adicione esta linha para conceder permissão de escrita ao job
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@0.9.0
        with:
          USERNAME: devmarlon2006 # Seu nome de usuário do GitHub
          OUTPUT_TYPE: "svg"
          # Não é necessário passar 'token: ${{ secrets.GITHUB_TOKEN }}' explicitamente
          # a menos que você esteja usando um token diferente ou tenha problemas com o padrão.
      - name: Push to README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "Generated 3D Contribution Graph" || echo "No changes to commit"
          git push