name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: yoshi389111/github-profile-3d-contrib@main
        with:
          USERNAME: devmarlon2006
          OUTPUT_TYPE: "svg"
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to README
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A .
          git commit -m "Generated 3D Contribution Graph" || echo "No changes to commit"
          git push